name: Update Tweets Data

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight

jobs:
  update-tweets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun sync hard-tweets
      - run: bun sync users
